### ISSUE TITLE
Manifestation of Spells

### ISSUE THREAD

**Issue by DonaldTsang** [metriccaution/dnd-spell-cards#6]
The link  https://www.dnd-spells.com/spells allows people to make spells book PDFs by filtering and sorting spells. It would be good to create such a feature for those who love physical.

**Comment by metriccaution** [comment]
I'm not quite sure what you're suggesting here.

Are you imagining this being a print view for the page? Or some way of building a custom pre-filtered list of spells?

I'm definitely willing to have a look at something to make this work for you (although probably after I've had a chance to look into the poor search performance), but I'd appreciate a clearer description of what you're after.

Thanks for raising the issue!

**Comment by DonaldTsang** [comment]
Yeah, not just a print view, but an actual PDF meant for reading spells of a certain characteristics easily.

**Comment by metriccaution** [comment]
Sorry, but I'm still not quite sure what you're asking for - Could you talk me through how you'd see this being used please.
