### ISSUE TITLE
Larger Spell Collection

### ISSUE THREAD

**Issue by DonaldTsang** [metriccaution/dnd-spell-cards#7]
There are more spells than the Player's Handbook, might be a good idea to include them.
- https://donjon.bin.sh/5e/spells/ (has 4 sources)
- https://dnd5spells.rpgist.net/en/spells (has 10 sources)
- https://roll20.net/compendium/dnd5e/Spells%20List (has 8 sources)

**Comment by metriccaution** [comment]
Hi, short answer is that this is really a licensing issue, and I'm not willing to either publish a copy of, or receive pull requests for unlicensed copyrighted material.

- The [System Reference Document](https://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf) is, to my knowledge the only WotC source available under the _Open Gaming License_ 
    - To my reading, this allows for use in this style of application
- The Player's Handbook is unlicensed for general use
- I believe this is also the case for other WotC material, e.g. _Elemental Evil_ or _Xanathar's Guide to Everything_

I'm not sure if the other sites you're referencing have their own arrangements in place, but this isn't a risk that I'm willing to take here.

The good news is that if you have your own copy of this material, in the correct format, you can make use of it in the web page using the `Browse` button in the sidebar, although this feature is currently undocumented and is somewhat fiddly to use.

**Comment by DonaldTsang** [comment]
In that case it would b good to just include the 4 sources that are unlicensed by WotC (i.e.the ones in https://donjon.bin.sh/5e/spells/ and https://www.dnd-spells.com/spells ).

I will also check if the others listed in RPGist or Roll20 are allowed by getting in contact with them.

**Comment by metriccaution** [comment]
Just to clarify, unlicensed in this case means _I don't have a license to use them_, as far as I can see, this applies to all the sources you've listed.

If you think this isn't the case, please point me in the direction of some documentation that says otherwise.
